CREATE TABLE users (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  mail VARCHAR(255) NULL,
  pseudo VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(764) NOT NULL,
  wins SMALLINT NULL DEFAULT 0,
  pbtime TIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
