const list = [
  {
    id: 1,
    src: "https://robohash.org/009.png?set=set4&size=90x90",
    criteria: ["dark yellow", "headAccessories", "glasses"],
    active: true,
  },
  {
    id: 2,
    src: "https://robohash.org/4O3.png?set=set4&size=90x90",
    criteria: ["white", "collar"],
    active: true,
  },
  {
    id: 3,
    src: "https://robohash.org/300.png?set=set4&size=90x90",
    criteria: ["dark red", "headAccessories"],
    active: true,
  },
  {
    id: 4,
    src: "https://robohash.org/303.png?set=set4&size=90x90",
    criteria: ["dark yellow", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 5,
    src: "https://robohash.org/031.png?set=set4&size=90x90",
    criteria: ["yellow", "headAccessories", "glasses"],
    active: true,
  },
  {
    id: 6,
    src: "https://robohash.org/301.png?set=set4&size=90x90",
    criteria: ["orange", "glasses", "collar"],
    active: true,
  },
  {
    id: 7,
    src: "https://robohash.org/130.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "collar"],
    active: true,
  },
  {
    id: 8,
    src: "https://robohash.org/155.png?set=set4&size=90x90",
    criteria: ["white", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 9,
    src: "https://robohash.org/181.png?set=set4&size=90x90",
    criteria: ["orange", "no spots", "headAccessories"],
    active: true,
  },
  {
    id: 10,
    src: "https://robohash.org/999.png?set=set4&size=90x90",
    criteria: ["white", "spots", "headAccessories", "glasses"],
    active: true,
  },
  {
    id: 11,
    src: "https://robohash.org/456.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 12,
    src: "https://robohash.org/924.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "collar"],
    active: true,
  },
  {
    id: 13,
    src: "https://robohash.org/365.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 14,
    src: "https://robohash.org/077.png?set=set4&size=90x90",
    criteria: ["dark yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 15,
    src: "https://robohash.org/067.png?set=set4&size=90x90",
    criteria: ["white", "spots", "collar"],
    active: true,
  },
  {
    id: 16,
    src: "https://robohash.org/712.png?set=set4&size=90x90",
    criteria: ["dark red", "spots", "collar"],
    active: true,
  },
  {
    id: 17,
    src: "https://robohash.org/387.png?set=set4&size=90x90",
    criteria: ["yellow", "collar", "glasses"],
    active: true,
  },
  {
    id: 18,
    src: "https://robohash.org/104.png?set=set4&size=90x90",
    criteria: ["pink", "headAccessories"],
    active: true,
  },
  {
    id: 19,
    src: "https://robohash.org/508.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 20,
    src: "https://robohash.org/234.png?set=set4&size=90x90",
    criteria: ["orange", "collar"],
    active: true,
  },
  {
    id: 21,
    src: "https://robohash.org/082.png?set=set4&size=90x90",
    criteria: ["dark red", "spots"],
    active: true,
  },
  {
    id: 22,
    src: "https://robohash.org/138.png?set=set4&size=90x90",
    criteria: ["white", "glasses", "headAccessories"],
    active: true,
  },
  {
    id: 23,
    src: "https://robohash.org/140.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "glasses", "headAccessories"],
    active: true,
  },
  {
    id: 24,
    src: "https://robohash.org/008.png?set=set4&size=90x90",
    criteria: ["dark yellow", "collar"],
    active: true,
  },
  {
    id: 25,
    src: "https://robohash.org/905.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 26,
    src: "https://robohash.org/174.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 27,
    src: "https://robohash.org/030.png?set=set4&size=90x90",
    criteria: ["dark red", "glasses"],
    active: true,
  },
  {
    id: 28,
    src: "https://robohash.org/106.png?set=set4&size=90x90",
    criteria: ["pink", "collar"],
    active: true,
  },
  {
    id: 29,
    src: "https://robohash.org/123.png?set=set4&size=90x90",
    criteria: ["dark yellow", "headAccessories"],
    active: true,
  },
  {
    id: 30,
    src: "https://robohash.org/197.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "collar", "glasses"],
    active: true,
  },
  {
    id: 31,
    src: "https://robohash.org/406.png?set=set4&size=90x90",
    criteria: ["dark red", "spots", "glasses", "collar"],
    active: true,
  },
  {
    id: 32,
    src: "https://robohash.org/689.png?set=set4&size=90x90",
    criteria: ["yellow", "headAccessories"],
    active: true,
  },
  {
    id: 33,
    src: "https://robohash.org/502.png?set=set4&size=90x90",
    criteria: ["yellow", "collar", "spots"],
    active: true,
  },
  {
    id: 34,
    src: "https://robohash.org/511.png?set=set4&size=90x90",
    criteria: ["orange", "headAccessories", "spots"],
    active: true,
  },
  {
    id: 35,
    src: "https://robohash.org/531.png?set=set4&size=90x90",
    criteria: ["dark yellow", "collar", "spots"],
    active: true,
  },
  {
    id: 36,
    src: "https://robohash.org/519.png?set=set4&size=90x90",
    criteria: ["dark red", "headAccessories", "spots"],
    active: true,
  },
  {
    id: 37,
    src: "https://robohash.org/520.png?set=set4&size=90x90",
    criteria: ["yellow", "headAccessories", "spots"],
    active: true,
  },
  {
    id: 38,
    src: "https://robohash.org/534.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "glasses"],
    active: true,
  },
  {
    id: 39,
    src: "https://robohash.org/536.png?set=set4&size=90x90",
    criteria: ["white", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 40,
    src: "https://robohash.org/538.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "collar"],
    active: true,
  },
  {
    id: 41,
    src: "https://robohash.org/540.png?set=set4&size=90x90",
    criteria: ["dark red", "glasses", "spots"],
    active: true,
  },
  {
    id: 42,
    src: "https://robohash.org/557.png?set=set4&size=90x90",
    criteria: ["white", "spots", "glasses", "headAccessories"],
    active: true,
  },
  {
    id: 43,
    src: "https://robohash.org/550.png?set=set4&size=90x90",
    criteria: ["orange", "headAccessories"],
    active: true,
  },
  {
    id: 44,
    src: "https://robohash.org/562.png?set=set4&size=90x90",
    criteria: ["dark yellow", "glasses", "collar", "spots"],
    active: true,
  },
  {
    id: 45,
    src: "https://robohash.org/548.png?set=set4&size=90x90",
    criteria: ["dark red", "collar"],
    active: true,
  },
  {
    id: 46,
    src: "https://robohash.org/563.png?set=set4&size=90x90",
    criteria: ["orange", "collar", "glasses", "spots"],
    active: true,
  },
  {
    id: 47,
    src: "https://robohash.org/571.png?set=set4&size=90x90",
    criteria: ["dark red", "headAccessories"],
    active: true,
  },
  {
    id: 48,
    src: "https://robohash.org/575.png?set=set4&size=90x90",
    criteria: ["white", "headAccessories"],
    active: true,
  },
  {
    id: 49,
    src: "https://robohash.org/578.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 50,
    src: "https://robohash.org/590.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "collar", "glasses"],
    active: true,
  },
  {
    id: 51,
    src: "https://robohash.org/599.png?set=set4&size=90x90",
    criteria: ["dark red", "glasses", "collar"],
    active: true,
  },
  {
    id: 52,
    src: "https://robohash.org/604.png?set=set4&size=90x90",
    criteria: ["dark yellow", "headAccessories", "spots"],
    active: true,
  },
  {
    id: 53,
    src: "https://robohash.org/598.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "headAccessories", "glasses"],
    active: true,
  },
  {
    id: 54,
    src: "https://robohash.org/626.png?set=set4&size=90x90",
    criteria: ["white", "headAccessories"],
    active: true,
  },
  {
    id: 55,
    src: "https://robohash.org/695.png?set=set4&size=90x90",
    criteria: ["pink", "collar"],
    active: true,
  },
  {
    id: 56,
    src: "https://robohash.org/728.png?set=set4&size=90x90",
    criteria: ["dark yellow", "glasses", "headAccessories"],
    active: true,
  },
  {
    id: 57,
    src: "https://robohash.org/606.png?set=set4&size=90x90",
    criteria: ["yellow", "headAccessories", "spots"],
    active: true,
  },
  {
    id: 58,
    src: "https://robohash.org/736.png?set=set4&size=90x90",
    criteria: ["white", "spots", "collar"],
    active: true,
  },
  {
    id: 59,
    src: "https://robohash.org/705.png?set=set4&size=90x90",
    criteria: ["pink", "headAccessories", "glasses", "spots"],
    active: true,
  },
  {
    id: 60,
    src: "https://robohash.org/739.png?set=set4&size=90x90",
    criteria: ["dark red", "glasses", "headAccessories"],
    active: true,
  },
  {
    id: 61,
    src: "https://robohash.org/748.png?set=set4&size=90x90",
    criteria: ["white", "spots", "headAccessories"],
    active: true,
  },
  {
    id: 62,
    src: "https://robohash.org/768.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "glasses", "collar"],
    active: true,
  },
  {
    id: 63,
    src: "https://robohash.org/785.png?set=set4&size=90x90",
    criteria: ["dark yellow", "headAccessories", "glasses", "spots"],
    active: true,
  },
  {
    id: 64,
    src: "https://robohash.org/829.png?set=set4&size=90x90",
    criteria: ["yellow"],
    active: true,
  },
  {
    id: 65,
    src: "https://robohash.org/873.png?set=set4&size=90x90",
    criteria: ["yellow", "collar"],
    active: true,
  },
  {
    id: 66,
    src: "https://robohash.org/1076.png?set=set4&size=90x90",
    criteria: ["dark yellow", "collar"],
  },
];

export default list;
