const list = [
  {
    id: 1,
    src: "https://robohash.org/009.png?set=set4&size=90x90",
    criteria: ["dark yellow", "no spots", "accessories", "glasses"],
    active: true,
  },
  {
    id: 2,
    src: "https://robohash.org/4O3.png?set=set4&size=90x90",
    criteria: ["white", "no spots", "collar"],
    active: true,
  },
  {
    id: 3,
    src: "https://robohash.org/300.png?set=set4&size=90x90",
    criteria: ["dark red", "no spots", "accessories"],
    active: true,
  },
  {
    id: 4,
    src: "https://robohash.org/303.png?set=set4&size=90x90",
    criteria: ["dark yellow", "spots", "accessories"],
    active: true,
  },
  {
    id: 5,
    src: "https://robohash.org/031.png?set=set4&size=90x90",
    criteria: ["yellow", "no spots", "accessories", "glasses"],
    active: true,
  },
  {
    id: 6,
    src: "https://robohash.org/301.png?set=set4&size=90x90",
    criteria: ["orange", "no spots", "glasses", "collar"],
    active: true,
  },
  {
    id: 7,
    src: "https://robohash.org/130.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "collar"],
    active: true,
  },
  {
    id: 8,
    src: "https://robohash.org/155.png?set=set4&size=90x90",
    criteria: ["white", "spots", "accessories"],
    active: true,
  },
  {
    id: 9,
    src: "https://robohash.org/181.png?set=set4&size=90x90",
    criteria: ["orange", "no spots", "accessories"],
    active: true,
  },
  {
    id: 10,
    src: "https://robohash.org/999.png?set=set4&size=90x90",
    criteria: ["white", "spots", "accessories", "glasses"],
    active: true,
  },
  {
    id: 11,
    src: "https://robohash.org/456.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 12,
    src: "https://robohash.org/924.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "collar"],
    active: true,
  },
  {
    id: 13,
    src: "https://robohash.org/365.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "accessories"],
    active: true,
  },
  {
    id: 14,
    src: "https://robohash.org/077.png?set=set4&size=90x90",
    criteria: ["dark yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 15,
    src: "https://robohash.org/067.png?set=set4&size=90x90",
    criteria: ["white", "spots", "collar"],
    active: true,
  },
  {
    id: 16,
    src: "https://robohash.org/712.png?set=set4&size=90x90",
    criteria: ["dark red", "spots", "collar"],
    active: true,
  },
  {
    id: 17,
    src: "https://robohash.org/387.png?set=set4&size=90x90",
    criteria: ["yellow", "no spots", "collar", "glasses"],
    active: true,
  },
  {
    id: 18,
    src: "https://robohash.org/104.png?set=set4&size=90x90",
    criteria: ["pink", "no spots", "accessories"],
    active: true,
  },
  {
    id: 19,
    src: "https://robohash.org/508.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "accessories"],
    active: true,
  },
  {
    id: 20,
    src: "https://robohash.org/234.png?set=set4&size=90x90",
    criteria: ["orange", "no spots", "collar"],
    active: true,
  },
  {
    id: 21,
    src: "https://robohash.org/082.png?set=set4&size=90x90",
    criteria: ["dark red", "spots"],
    active: true,
  },
  {
    id: 22,
    src: "https://robohash.org/138.png?set=set4&size=90x90",
    criteria: ["white", "no spots", "glasses", "accessories"],
    active: true,
  },
  {
    id: 23,
    src: "https://robohash.org/140.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "glasses", "accessories"],
    active: true,
  },
  {
    id: 24,
    src: "https://robohash.org/008.png?set=set4&size=90x90",
    criteria: ["dark yellow", "no spots", "collar"],
    active: true,
  },
  {
    id: 25,
    src: "https://robohash.org/905.png?set=set4&size=90x90",
    criteria: ["orange", "spots", "accessories"],
    active: true,
  },
  {
    id: 26,
    src: "https://robohash.org/174.png?set=set4&size=90x90",
    criteria: ["yellow", "spots", "collar"],
    active: true,
  },
  {
    id: 27,
    src: "https://robohash.org/030.png?set=set4&size=90x90",
    criteria: ["dark red", "no spots", "glasses"],
    active: true,
  },
  {
    id: 28,
    src: "https://robohash.org/106.png?set=set4&size=90x90",
    criteria: ["pink", "no spots", "collar"],
    active: true,
  },
  {
    id: 29,
    src: "https://robohash.org/123.png?set=set4&size=90x90",
    criteria: ["dark yellow", "no spots", "accessories"],
    active: true,
  },
  {
    id: 30,
    src: "https://robohash.org/197.png?set=set4&size=90x90",
    criteria: ["pink", "spots", "collar", "glasses"],
    active: true,
  },
  {
    id: 31,
    src: "https://robohash.org/406.png?set=set4&size=90x90",
    criteria: ["dark red", "spots", "glasses", "collar"],
    active: true,
  },
  {
    id: 32,
    src: "https://robohash.org/689.png?set=set4&size=90x90",
    criteria: ["yellow", "no spots", "accessories"],
    active: true,
  },
];

export default list;
